"""Deterministic report-processing MCP server for Day 20."""

from __future__ import annotations

from collections import Counter
from typing import Annotated, Any

from mcp.server.fastmcp import FastMCP
from pydantic import Field


def build_report_server() -> FastMCP:
    """Build the isolated report server with no LLM dependencies."""

    server = FastMCP("AI Advent Orchestration Report")

    @server.tool(structured_output=True)
    def build_orchestration_report(
        tracker_data: Annotated[
            dict[str, Any], Field(description="Accumulated Tracker search/get results.")
        ],
        knowledge_context: Annotated[
            dict[str, Any], Field(description="Accumulated day contexts and practice notes.")
        ],
        flow_summary: Annotated[
            dict[str, Any], Field(description="Compact orchestration state and counters.")
        ],
        report_title: Annotated[
            str, Field(description="Markdown H1 title.")
        ] = "Week 04 MCP orchestration report",
    ) -> dict[str, Any]:
        """Build a deterministic Markdown report from gathered orchestration data."""

        issues = _collect_issues(tracker_data)
        status_counts = dict(
            sorted(Counter(item.get("status", "unknown") for item in issues).items())
        )
        issue_rows = (
            "\n".join(
                f"- `{item.get('issue_key', '?')}` — {item.get('title', 'Без названия')} "
                f"(`{item.get('status', 'unknown')}`). {item.get('summary', '')}"
                for item in issues
            )
            or "- Tracker data не содержит задач."
        )
        knowledge_rows = "\n".join(_knowledge_rows(knowledge_context)) or "- Контекст не собран."
        registered_servers = _format_servers(flow_summary.get("registered_servers"))
        data_source_servers = _format_servers(
            flow_summary.get("data_source_servers_used_before_report")
        )
        report_server = str(flow_summary.get("report_server", "report"))
        storage_server = str(flow_summary.get("storage_server", "storage"))
        flow_stage = str(flow_summary.get("flow_stage", "report_generation"))
        pre_report_calls = flow_summary.get("tool_calls_total_before_report", 0)
        markdown = f"""# {report_title.strip() or "MCP orchestration report"}

## Tracker

- Issues: `{len(issues)}`
- Status counts: `{status_counts}`

{issue_rows}

## Knowledge context

{knowledge_rows}

## MCP server topology

- Registered servers: `{registered_servers}`.
- Data sources used before report generation: `{data_source_servers}`.
- Current flow stage: `{flow_stage}`.
- Tool calls completed before report generation: `{pre_report_calls}`.
- Model-specific tool calling: `false`
- Hardcoded pipeline: `false`

This report is generated by the `{report_server}` MCP server. After report generation and next-step
processing, it is persisted through the `{storage_server}` MCP server as part of the complete
orchestration flow. The final trace, not this pre-storage snapshot, proves which servers were
actually invoked through completion.

## Итог

Данные собраны с независимых Tracker и Knowledge MCP servers, обработаны Report server и должны
быть сохранены через Storage server. Planner использует переносимый JSON action contract.
"""
        return {
            "title": report_title.strip() or "MCP orchestration report",
            "issue_count": len(issues),
            "status_counts": status_counts,
            "knowledge_items": len(_knowledge_rows(knowledge_context)),
            "registered_servers": flow_summary.get("registered_servers", []),
            "data_source_servers_used_before_report": flow_summary.get(
                "data_source_servers_used_before_report", []
            ),
            "report_server": report_server,
            "storage_server": storage_server,
            "markdown": markdown,
        }

    @server.tool(structured_output=True)
    def build_next_steps(
        tracker_data: Annotated[
            dict[str, Any], Field(description="Accumulated Tracker search/get results.")
        ],
        knowledge_context: Annotated[
            dict[str, Any], Field(description="Accumulated knowledge results.")
        ],
        report_summary: Annotated[
            dict[str, Any], Field(description="Summary returned by build_orchestration_report.")
        ],
    ) -> dict[str, Any]:
        """Build deterministic follow-up recommendations from already gathered data."""

        issues = _collect_issues(tracker_data)
        planned = [item.get("issue_key") for item in issues if item.get("status") == "planned"]
        steps = [
            "Проверить trace и routing decisions для каждого MCP tool call.",
            "Сверить SHA-256 финального Markdown и JSON state после storage save.",
            "Сохранить provider-neutral planner contract при замене LLM backend.",
        ]
        if planned:
            steps.insert(0, f"Завершить planned Tracker tasks: {', '.join(map(str, planned))}.")
        return {
            "next_steps": steps,
            "planned_issue_keys": planned,
            "source_issue_count": len(issues),
            "knowledge_item_count": len(_knowledge_rows(knowledge_context)),
            "report_title": report_summary.get("title"),
        }

    return server


def _collect_issues(tracker_data: dict[str, Any]) -> list[dict[str, Any]]:
    by_key: dict[str, dict[str, Any]] = {}
    for value in tracker_data.values():
        if not isinstance(value, dict):
            continue
        candidates = value.get("issues")
        if not isinstance(candidates, list):
            candidates = [value] if "issue_key" in value else []
        for issue in candidates:
            if isinstance(issue, dict) and isinstance(issue.get("issue_key"), str):
                by_key[issue["issue_key"]] = issue
    return [by_key[key] for key in sorted(by_key)]


def _knowledge_rows(knowledge_context: dict[str, Any]) -> list[str]:
    rows: list[str] = []
    for key, value in sorted(knowledge_context.items()):
        if isinstance(value, dict):
            rows.append(f"- `{key}` — {value.get('title', 'Контекст')}: {value.get('summary', '')}")
    return rows


def _format_servers(value: Any) -> str:
    if not isinstance(value, list):
        return "нет"
    servers = [str(item) for item in value]
    return "`, `".join(servers) if servers else "нет"


mcp = build_report_server()
